#if 0
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_uav_structured_opc u0, 4
dcl_uav_typed_buffer (uint,uint,uint,uint) u1
dcl_input vThreadID.x
dcl_temps 1
dcl_thread_group 4, 1, 1
imm_atomic_alloc r0.x, u0
iadd r0.y, r0.x, l(98)
store_structured u0.x, r0.x, l(0), r0.y
store_uav_typed u1.xyzw, vThreadID.xxxx, r0.xxxx
ret
// Approximately 0 instruction slots used
#endif

const BYTE g_counter_producer_cs[] =
{
     68,  88,  66,  67, 142,   7,
    198,  56, 153,  30, 188, 194,
    195, 155, 122,  69, 102, 161,
    204, 248,   1,   0,   0,   0,
     16,   1,   0,   0,   3,   0,
      0,   0,  44,   0,   0,   0,
     60,   0,   0,   0,  76,   0,
      0,   0,  73,  83,  71,  78,
      8,   0,   0,   0,   0,   0,
      0,   0,   8,   0,   0,   0,
     79,  83,  71,  78,   8,   0,
      0,   0,   0,   0,   0,   0,
      8,   0,   0,   0,  83,  72,
     69,  88, 188,   0,   0,   0,
     80,   0,   5,   0,  47,   0,
      0,   0, 106,   8,   0,   1,
    158,   0, 128,   4,   0, 224,
     17,   0,   0,   0,   0,   0,
      4,   0,   0,   0, 156,   8,
      0,   4,   0, 224,  17,   0,
      1,   0,   0,   0,  68,  68,
      0,   0,  95,   0,   0,   2,
     18,   0,   2,   0, 104,   0,
      0,   2,   1,   0,   0,   0,
    155,   0,   0,   4,   4,   0,
      0,   0,   1,   0,   0,   0,
      1,   0,   0,   0, 178,   0,
      0,   5,  18,   0,  16,   0,
      0,   0,   0,   0,   0, 224,
     17,   0,   0,   0,   0,   0,
     30,   0,   0,   7,  34,   0,
     16,   0,   0,   0,   0,   0,
     10,   0,  16,   0,   0,   0,
      0,   0,   1,  64,   0,   0,
     98,   0,   0,   0, 168,   0,
      0,   9,  18, 224,  17,   0,
      0,   0,   0,   0,  10,   0,
     16,   0,   0,   0,   0,   0,
      1,  64,   0,   0,   0,   0,
      0,   0,  26,   0,  16,   0,
      0,   0,   0,   0, 164,   0,
      0,   6, 242, 224,  17,   0,
      1,   0,   0,   0,   6,   0,
      2,   0,   6,   0,  16,   0,
      0,   0,   0,   0,  62,   0,
      0,   1
};
