#if 0
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_uav_structured_opc u0, 4
dcl_uav_typed_buffer (uint,uint,uint,uint) u1
dcl_input vThreadID.x
dcl_temps 1
dcl_thread_group 2, 1, 1
imm_atomic_consume r0.x, u0
ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r0.x, r0.x, l(0), u0.xxxx
store_uav_typed u1.xyzw, vThreadID.xxxx, r0.xxxx
ret
// Approximately 0 instruction slots used
#endif

const BYTE g_counter_consumer_cs[] =
{
     68,  88,  66,  67, 231, 185,
     73, 240,  29, 193,  90, 156,
    215,  51, 244,  96,  47, 177,
     33, 210,   1,   0,   0,   0,
    252,   0,   0,   0,   3,   0,
      0,   0,  44,   0,   0,   0,
     60,   0,   0,   0,  76,   0,
      0,   0,  73,  83,  71,  78,
      8,   0,   0,   0,   0,   0,
      0,   0,   8,   0,   0,   0,
     79,  83,  71,  78,   8,   0,
      0,   0,   0,   0,   0,   0,
      8,   0,   0,   0,  83,  72,
     69,  88, 168,   0,   0,   0,
     80,   0,   5,   0,  42,   0,
      0,   0, 106,   8,   0,   1,
    158,   0, 128,   4,   0, 224,
     17,   0,   0,   0,   0,   0,
      4,   0,   0,   0, 156,   8,
      0,   4,   0, 224,  17,   0,
      1,   0,   0,   0,  68,  68,
      0,   0,  95,   0,   0,   2,
     18,   0,   2,   0, 104,   0,
      0,   2,   1,   0,   0,   0,
    155,   0,   0,   4,   2,   0,
      0,   0,   1,   0,   0,   0,
      1,   0,   0,   0, 179,   0,
      0,   5,  18,   0,  16,   0,
      0,   0,   0,   0,   0, 224,
     17,   0,   0,   0,   0,   0,
    167,   0,   0, 139,   2,  35,
      0, 128, 131, 153,  25,   0,
     18,   0,  16,   0,   0,   0,
      0,   0,  10,   0,  16,   0,
      0,   0,   0,   0,   1,  64,
      0,   0,   0,   0,   0,   0,
      6, 224,  17,   0,   0,   0,
      0,   0, 164,   0,   0,   6,
    242, 224,  17,   0,   1,   0,
      0,   0,   6,   0,   2,   0,
      6,   0,  16,   0,   0,   0,
      0,   0,  62,   0,   0,   1
};
